// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqcgrqjucmdojzanemwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxY2dycWp1Y21kb2p6YW5lbXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMjc0NjksImV4cCI6MjA1OTcwMzQ2OX0.isjpmrExC4CiaBrF__Y3LBwRJ2dUf012Lt9awq-G9Xs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);